# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Application Services Design
# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/appservices-design-poc/" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: "pmarsceill/just-the-docs@v0.2.7"
# plugins:
#  - jekyll-feed

# logo: "/assets/images/logo.png"
# defaults:
#   -
#     scope:
#       path: "designs"
#     values:
#       permalink: /:title

#  aux_links:
#    "GitHub repo":
#      - "//github.com/openshift/openshift-origin-design"
#  footer_content: "<a href=\"https://www.redhat.com/en/about/open-source\">Open Source</a> - <a href=\"https://github.com/openshift/openshift-origin-design/blob/master/LICENSE\">Apache License 2.0</a>"
# Footer metadata
# show_last_edit_time: true
# last_edit_time_format: "%b %e %Y at %I:%M %p"
# show_gh_edit_link: true
# gh_edit_repository: "https://github.com/openshift/openshift-origin-design"
# edit_link_text: "Edit this page on GitHub."
